### ISSUE TITLE
SIM complete purchase response

### ISSUE THREAD

**Issue by lukeholder** [thephpleague/omnipay-authorizenet#116]
Whenever other omnipay gateways return `isSuccessful() = true` they NEVER also return `isRedirect() = true`

See:

https://github.com/thephpleague/omnipay-multisafepay/issues/19

SIM complete purchase breaks that omnipay convention.

Not sure how we could fix this in any backwards compatible way?

**Comment by judgej** [comment]
I think `isRedirect()` needs to be made conditional, just like `isSuccessful()` is in the same class:

https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/SIMCompleteAuthorizeResponse.php#L60

That shouldn't break anything, because people shouldn't be redirecting when there is no reason to redirect anyway, so I'm assuming this change would not hit any working code.

**Comment by lukeholder** [comment]
We have gotten around this just by treating SIM differently. It just meant we couldn't treat it like all other gateways. Due to our changes SIM is now working for us, so I will leave it to you to decide to update omnipay.

Thanks @judgej
