### ISSUE TITLE
Transaction ID

### ISSUE THREAD

**Issue by hexarmorkyledye** [thephpleague/omnipay-authorizenet#28]
Which method should I use to get the transaction ID?  I am already getting the authorization code, but don't I need both to settle?  Thank you.

**Comment by judgej** [comment]
At a guess, I suspect you need `getTransactionReference()` - but I'm making some assumptions here.

The "transaction reference" in OmniPay is the ID that the the remote gateway gives to a transaction. This happens to be called "Transaction ID" in Authorize.Net. Is that would you were looking for?

**Comment by delatbabel** [comment]
The answer is that you should use whatever data from the response you need to have to request a void or a refund of a transaction, and that is the reference that should be returned by getTransactionReference() in all plugins.

As an example, MultiCards send back multiple data items -- transaction ID, order number, customer reference, token ID, etc. However it's the transaction ID that is required to refund or void a transaction, so that is the one that should be returned by getTransactionReference().

We like to assume (although it's not always the case) that we can do this:

```php
$purchaseResponse = $gateway->purchase($data)->send();
$transactionReference = $purchaseResponse->getTransactionReference();
$voidResponse = $gateway->void(['transactionReference' => $transactionReference])->send();
```

... of course including the various isSuccessful() checks and exception handlers along the way.
