### ISSUE TITLE
AIMResponse::getMessage() returns blank when an [authentication] error occurs. 

### ISSUE THREAD

**Issue by hillelcoren** [thephpleague/omnipay-authorizenet#40]
It looks like [the code](https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/AIMResponse.php#L84) is expecting the value to be returned as messages[0]->message[0]->description or errors[0]->error[0]->errorText. When testing it appears as messages[0]->message[0]->text.

Here's a sample response: 

SimpleXMLElement {#1025 ▼
  +"refId": "0001"
  +"messages": SimpleXMLElement {#848 ▼
    +"resultCode": "Error"
    +"message": SimpleXMLElement {#851 ▼
      +"code": "E00007"
      +"text": "User authentication failed due to invalid authentication values."
    }
  }
  +"transactionResponse": SimpleXMLElement {#849}
}

**Comment by judgej** [comment]
I see this result too, but I have also seen the error message correctly returned, probably when `errors` are returned rather than `messages`.

I think the code is actually looking in `description` when it should be looking in `text`.

I'll check the specs and see what the definitive places to look for error text/message/descriptions are.

~~~php
object(SimpleXMLElement)#172 (3) {
  ["refId"]=>
  string(8) "09876786"
  ["messages"]=>
  object(SimpleXMLElement)#394 (2) {
    ["resultCode"]=>
    string(5) "Error"
    ["message"]=>
    object(SimpleXMLElement)#396 (2) {
      ["code"]=>
      string(6) "E00007"
      ["text"]=>
      string(64) "User authentication failed due to invalid authentication values."
    }
  }
  ["transactionResponse"]=>
  object(SimpleXMLElement)#395 (0) {
  }
}
~~~

There are a couple things this highlights that may be useful more generically in OmniPay:

* Both `messages` and `errors` can return multiple messages and errors. This gateway only returns the first it finds. When submitting transactions and validation fails, many gateways can return multiple validation errors and not just one.
* The OmniPay core needs some way to easily and safely navigate these data structures, some of which can be quite deep. The laraval `dataget()` helper function is one good example.

I have pinched `dataget()` to use in a Sage Pay gateway here: https://github.com/academe/SagePay-Integration/blob/PSR-7/src/Helper.php#L23 It can turn this:

    (string)$this->data->transactionResponse[0]->messages[0]->message[0]->description

into this:

    (string)dataget($this, 'data.transactionResponse.0.messages.0.message.0.description', null)

The dot-notation does nor care whether the data is an array or an object. For objects it can be made to automatically check for properties or getter functions. Its main feature is that it can walk the structure until it either finds the final node, or runs out of structure, and do so without throwing exceptions. Anyway, that's kind of an aside, but just thought I'd note it down here while I thought about it.

**Comment by judgej** [comment]
[This guide](www.authorize.net/content/dam/authorize/documents/AIM_guide_XML.pdf) seems to indicate the results can include:

~~~json
errors: [
        {error: {
            errorCode: "error-code",
            errorText: "error-text"
        }}
        , ...
    ]
~~~

or 

~~~json
messages: [
        {message: {
            code: "message-code",
            description: "message-text"
        }}
        , ...
    ]
~~~

So the gateway driver code seems to be following the specs. However, there is another part of the spec that lists `text` as the message text instead of `descrioption`. I think that is for messages returned from a different part of the gateway (the authorisation part rather than the transaction processing part).

~~~json
        message: {
            code: "message-code",
            text: "message-text"
        }
~~~

It's a slightly different structure too  - not in a `messages` array. So in essence, we have THREE potential fields to check for the error message text.

**Comment by judgej** [comment]
I've created new branch https://github.com/thephpleague/omnipay-authorizenet/tree/issue40 with a first fix - it looks for an error message and error code in this third possible location.

Now, I noticed in there that the response code is being cast to an `intval`. Since the codes look like `E00007` that is not really going to work, so it does looks like there are some further tweaks needed here. We'll do those fixes in this same issue, and also get some tests done. Not got much time for that today, but if you can try out the `issue40` branch, that would be a big help.

**Comment by hillelcoren** [comment]
The change looks good, I'm seeing the error details.

Thanks for the quick fix!

**Comment by judgej** [comment]
np - thanks for trying it out - it still needs tests, and we need to check if the other (non-authentication) errors are reported properly, before it gets merged in and released.

**Comment by judgej** [comment]
I think basically the rules are like this:

* Every response as a `messages` element with one or messages giving the result of the request. The codes for these messages is *not* numeric.
* If there is a `transactionResponse` then in there will be either `messages` or `errors`, depending on whether the transaction was successful or not. We need to grab whichever are available. The error or message code will be numeric.
* If there is no `transactionResponse` then authentication to the gateway failed, and only the messages with the non-numeric code will be available.

That last instance was what you reported in this issue, and we were not falling back to that error message. Now we do, however we are now picking up the non-numeric code in this instance, since there is no numeric transaction result code. I am unsure if this is the right thing to do. I *think* we perhaps need to be able to return *both* error codes and messages, as they are targeted at different parts of the process.

This is how the documentation describes them:

> There are two <message> elements: one is inside the <messages> element at the
beginning of the response and describes the status of your request; the other is within the
<transactionResponse> element and describes the status of the original transaction.

**Comment by daniel-farina** [comment]
This could work as temporary fix, it returns additional errors from the SDK instead of returning Trying to get property of non-object" exception

https://github.com/daniel-farina/omnipay-authorizenet/commit/7394a6045d677ee9cbe78a8bf9910c97644b0983

**Comment by judgej** [comment]
Throwing some examples of responses here:

Invalid auth code:
==================

resultCode = 0

````php
object(SimpleXMLElement)#39 (3) {
  ["refId"]=>
  string(9) "458785372"
  ["messages"]=>
  object(SimpleXMLElement)#23 (2) {
    ["resultCode"]=>
    string(5) "Error"
    ["message"]=>
    object(SimpleXMLElement)#61 (2) {
      ["code"]=>
      string(6) "E00007"
      ["text"]=>
      string(64) "User authentication failed due to invalid authentication values."
    }
  }
  ["transactionResponse"]=>
  object(SimpleXMLElement)#26 (0) {
  }
}
```

Address 1 too long:
===================

resultCode = 0

*** AND the error to fix:***

Notice:  Trying to get property of non-object in /var/www/vhosts/acadweb.co.uk/httpdocs/authorizenet/dev/omnipay-authorizenet/src/Message/AIMResponse.php on line 51

````php
object(SimpleXMLElement)#39 (1) {
  ["messages"]=>
  object(SimpleXMLElement)#23 (2) {
    ["resultCode"]=>
    string(5) "Error"
    ["message"]=>
    object(SimpleXMLElement)#26 (2) {
      ["code"]=>
      string(6) "E00003"
      ["text"]=>
      string(503) "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:address' element is invalid - The value '99 very long indeed intentionally too long 99 very long indeed intentionally too long 99 very long indeed intentionally too long 99 very long indeed intentionally too long 99 very long indeed intentionally too long 99 very long indeed intentionally too long 99 very long indeed intentionally too long  
Address 2S' is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value."
    }
  }
}
```

Successful:
===========

resultCode = 1

````php
object(SimpleXMLElement)#39 (3) {
  ["refId"]=>
  string(9) "976376168"
  ["messages"]=>
  object(SimpleXMLElement)#23 (2) {
    ["resultCode"]=>
    string(2) "Ok"
    ["message"]=>
    object(SimpleXMLElement)#61 (2) {
      ["code"]=>
      string(6) "I00001"
      ["text"]=>
      string(11) "Successful."
    }
  }
  ["transactionResponse"]=>
  object(SimpleXMLElement)#26 (13) {
    ["responseCode"]=>
    string(1) "1"
    ["authCode"]=>
    string(6) "000000"
    ["avsResultCode"]=>
    string(1) "P"
    ["cvvResultCode"]=>
    object(SimpleXMLElement)#61 (0) {
    }
    ["cavvResultCode"]=>
    object(SimpleXMLElement)#60 (0) {
    }
    ["transId"]=>
    string(1) "0"
    ["refTransID"]=>
    object(SimpleXMLElement)#62 (0) {
    }
    ["transHash"]=>
    string(32) "480AA04BE6E4BF0469B63D9E42BD568A"
    ["testRequest"]=>
    string(1) "1"
    ["accountNumber"]=>
    string(8) "XXXX4242"
    ["accountType"]=>
    string(4) "Visa"
    ["messages"]=>
    object(SimpleXMLElement)#63 (1) {
      ["message"]=>
      object(SimpleXMLElement)#76 (2) {
        ["code"]=>
        string(1) "1"
        ["description"]=>
        string(35) "This transaction has been approved."
      }
    }
    ["transHashSha2"]=>
    object(SimpleXMLElement)#64 (0) {
    }
  }
}
```

Amount Too Large:
=================

resultCode = 3

````php
object(SimpleXMLElement)#39 (3) {
  ["refId"]=>
  string(9) "578582369"
  ["messages"]=>
  object(SimpleXMLElement)#23 (2) {
    ["resultCode"]=>
    string(5) "Error"
    ["message"]=>
    object(SimpleXMLElement)#61 (2) {
      ["code"]=>
      string(6) "E00027"
      ["text"]=>
      string(33) "The transaction was unsuccessful."
    }
  }
  ["transactionResponse"]=>
  object(SimpleXMLElement)#26 (13) {
    ["responseCode"]=>
    string(1) "3"
    ["authCode"]=>
    string(6) "000000"
    ["avsResultCode"]=>
    string(1) "P"
    ["cvvResultCode"]=>
    object(SimpleXMLElement)#61 (0) {
    }
    ["cavvResultCode"]=>
    object(SimpleXMLElement)#60 (0) {
    }
    ["transId"]=>
    string(1) "0"
    ["refTransID"]=>
    object(SimpleXMLElement)#62 (0) {
    }
    ["transHash"]=>
    string(32) "F68A9C87C1E1472521704EF38C21F647"
    ["testRequest"]=>
    string(1) "1"
    ["accountNumber"]=>
    object(SimpleXMLElement)#63 (0) {
    }
    ["accountType"]=>
    object(SimpleXMLElement)#64 (0) {
    }
    ["errors"]=>
    object(SimpleXMLElement)#76 (1) {
      ["error"]=>
      object(SimpleXMLElement)#74 (2) {
        ["errorCode"]=>
        string(1) "5"
        ["errorText"]=>
        string(27) "A valid amount is required."
      }
    }
    ["transHashSha2"]=>
    object(SimpleXMLElement)#75 (0) {
    }
  }
}
```

**Comment by judgej** [comment]
In release 2.5.0
