### ISSUE TITLE
Description Option not being sent

### ISSUE THREAD

**Issue by bd86** [thephpleague/omnipay-authorizenet#43]
The description transaction option was not being set in AIMGateway. Created pull request #44

**Comment by bd86** [comment]
Created pull request #44

**Comment by judgej** [comment]
I'm trying this out in my test account, and I can't see the description getting through to the gateway at all - the transactions show up on the transaction search control panel as all empty.

The PR is also failing tests, and I'm not sure why. I suspect it may be the blank lines full of spaces that your editor puts in instead of just blank lines.

**Comment by judgej** [comment]
I can't get this PR to work, can't get the tests to pass locally (whether the tests are wrong or the driver is wrong, I really don't know). Travis tests are also failing. Personally can't afford to spend any more time on this PR.

**Comment by balexander** [comment]
@judgej I added a new pr that modifies bd86's code slightly.  Unit tests pass and I am seeing the description go through to Authorize.net

**Comment by judgej** [comment]
This has been merged now. I added the invoiceNumber at the same time, as it made sense. I couldn't find an invoice number field in OmniPay Common, though I could have sworn I remember there being one there. Probably just tired.

**Comment by judgej** [comment]
In release 2.5.0
