### ISSUE TITLE
Invoice number description and billing/shipping emails not being sent to AIMrequest

### ISSUE THREAD

**Issue by mariuskubilius** [thephpleague/omnipay-authorizenet#75]
I can not set the following fields using the library in current state:
Billing/Shipping e-mails
invoice number
description.
phone number.

**Comment by judgej** [comment]
@mariuskubilius Would you be able to give `dev-master` a try? That should support:

* `setInvoiceNumber()`
* `setDescription()`
* `$card->setBillingPhone()`

There are quite a few changes that I would like to put in a release soon. Nothing should be a BC break, but it needs to be tested in an environment other than mine (it works for me, but that's not enough, because I don't use many of the features).

**Comment by mariuskubilius** [comment]
Thanks will definitelly try 👍

**Comment by judgej** [comment]
Try release 2.5.0 That *should* fix all of the above. Let us know how it goes.

**Comment by judgej** [comment]
Closing this as fixed.
